// Données de démo partagées entre l'app et le serveur (prompts IA).
// Catalogues par métier : [désignation, réf, famille, fournisseur, achat HT, unité]
export const CAT_RAW = {
  elec: [
    ['Différentiel 30 mA type A 40 A','HAG-CDA742F','Tableau','CGED',38,'u'],
    ['Interrupteur diff. type AC 63 A','LEG-411617','Tableau','Rexel Réunion',32,'u'],
    ['Disjoncteur ph+N 16 A','SCH-A9N21024','Tableau','Rexel Réunion',6.2,'u'],
    ['Disjoncteur ph+N 20 A','SCH-A9N21025','Tableau','Rexel Réunion',6.5,'u'],
    ['Disjoncteur ph+N 32 A','SCH-A9N21027','Tableau','Rexel Réunion',7.8,'u'],
    ['Tableau 3 rangées 39 modules','HAG-VF313','Tableau','COREDIME',45,'u'],
    ['Coffret 13 modules','LEG-401211','Tableau','Ravate Pro',18,'u'],
    ['Peigne 13 modules','HAG-KB163P','Tableau','CGED',9,'u'],
    ['Parafoudre type 2','HAG-SPN215D','Tableau','CGED',75,'u'],
    ['Télérupteur 16 A','LEG-412408','Tableau','Rexel Réunion',14,'u'],
    ['Contacteur jour/nuit','HAG-ETC225','Tableau','COREDIME',28,'u'],
    ['Câble R2V 3G1,5','NEX-R2V3G15','Câbles','Rexel Réunion',1.1,'m'],
    ['Câble R2V 3G2,5','NEX-R2V3G25','Câbles','Rexel Réunion',1.6,'m'],
    ['Câble R2V 5G6','NEX-R2V5G6','Câbles','CGED',5.8,'m'],
    ['Gaine ICTA Ø20','ICTA-20','Câbles','COREDIME',0.55,'m'],
    ['Goulotte 40×40 2 m','LEG-GOU4040','Câbles','Ravate Pro',7.5,'u'],
    ['Prise 2P+T','LEG-MOS2PT','Appareillage','Ravate Pro',4.5,'u'],
    ['Interrupteur va-et-vient','LEG-MOSVV','Appareillage','Ravate Pro',4,'u'],
    ['Variateur LED','LEG-VARLED','Appareillage','Rexel Réunion',24,'u'],
    ['Prise RJ45 cat.6','LEG-RJ45C6','Appareillage','CGED',9,'u'],
    ['Spot LED 7 W','ARL-SPOT7','Éclairage','Ravate Pro',6,'u'],
    ['Hublot IP65','ARL-HUB65','Éclairage','Ravate',14,'u'],
    ['Détecteur de mouvement 360°','LEG-DET360','Éclairage','Rexel Réunion',26,'u'],
    ['Chauffe-eau 200 L stéatite','ATL-STEA200','Chauffe-eau & VMC','Téréva Réunion',290,'u'],
    ['VMC hygroréglable','ALD-VMCHY','Chauffe-eau & VMC','Téréva Réunion',95,'u'],
    ["Brasseur d'air + variateur",'RAV-BRAS132','Spécifique 974','Ravate',85,'u'],
    ['Coffret IP65 8 modules','HAG-IP658','Spécifique 974','CGED',24,'u'],
    ['Prise dédiée clim 20 A','LEG-CLIM20','Spécifique 974','Rexel Réunion',7,'u'],
    ["Boîte d'encastrement Ø67",'LEG-BE67','Accessoires','COREDIME',0.9,'u'],
    ['Piquet de terre + barrette','PIQ-TERRE','Accessoires','Ravate Pro',19,'u'],
  ],
  plomb: [
    ['WC suspendu + bâti','GEB-DUOFIX','Sanitaire','Téréva Réunion',240,'u'],
    ['Lavabo céramique 60 cm','JAC-ODEON60','Sanitaire','Téréva Réunion',65,'u'],
    ['Receveur de douche 90×90','KIN-REC90','Sanitaire','Ravate Pro',120,'u'],
    ['Mitigeur lavabo','GRO-EUROS','Robinetterie','Téréva Réunion',45,'u'],
    ['Mitigeur douche thermostatique','GRO-GROTH','Robinetterie','Téréva Réunion',110,'u'],
    ['Tube multicouche Ø16','HEN-MC16','Tuyauterie','Ravate Pro',2.4,'m'],
    ['Tube PER Ø16','PER-16','Tuyauterie','Ravate Pro',0.9,'m'],
    ['Raccord à sertir Ø16','HEN-RS16','Tuyauterie','Téréva Réunion',3.2,'u'],
    ['Chauffe-eau 200 L stéatite','ATL-STEA200','Chauffe-eau','Téréva Réunion',290,'u'],
    ['Tube PVC évacuation Ø40','PVC-40','Évacuation','Ravate',2.2,'m'],
    ['Siphon lavabo','NIC-SIPH32','Évacuation','Ravate',8,'u'],
    ['Groupe de sécurité','WAT-GS34','Sécurité','Téréva Réunion',22,'u'],
    ['Réducteur de pression','WAT-RDP34','Sécurité','Téréva Réunion',38,'u'],
    ['Bonde de douche Ø90','NIC-BON90','Évacuation','Ravate',18,'u'],
  ],
  macon: [
    ['Ciment CEM II 35 kg','LAF-CEM35','Liants','Ravate',11.5,'sac'],
    ['Chaux hydraulique 25 kg','LAF-NHL25','Liants','Ravate',14,'sac'],
    ['Parpaing 20×20×50','BLC-P20','Blocs','Négoce Sud',1.85,'u'],
    ['Brique creuse 20','BRI-C20','Blocs','Négoce Sud',2.6,'u'],
    ['Fer à béton HA10 12 m','FER-HA10','Ferraillage','Ravate',9.5,'u'],
    ['Treillis soudé ST25','TRE-ST25','Ferraillage','Ravate',38,'u'],
    ['Film polyane 150 µm','POL-150','Étanchéité','Ravate',1.2,'m²'],
    ['Sable 0/4 big-bag','GRA-S04','Granulats','Négoce Sud',65,'u'],
    ['Gravillon 6/10 big-bag','GRA-G610','Granulats','Négoce Sud',70,'u'],
    ['Hourdis béton 16','HOU-16','Hourdis','Négoce Sud',3.2,'u'],
    ["Étanchéité SEL 20 kg",'ETA-SEL20','Étanchéité','Ravate Pro',78,'u'],
  ],
  peintre: [
    ['Peinture acrylique mat 10 L','SEI-ACRM10','Peintures','Ravate Pro',62,'u'],
    ['Glycéro satin 2,5 L','SEI-GLY25','Peintures','Ravate Pro',38,'u'],
    ['Sous-couche 10 L','SEI-SC10','Sous-couches','Ravate',48,'u'],
    ['Enduit de rebouchage 5 kg','TOU-REB5','Sous-couches','Ravate',18,'u'],
    ['Bande à joint','PLA-BJ','Préparation','Ravate',3.5,'u'],
    ['Ruban de masquage','TES-RM50','Préparation','Ravate',3.2,'u'],
    ['Bâche de protection 4×5 m','BAC-45','Préparation','Ravate',4.5,'u'],
    ['Rouleau 180 mm','ROU-180','Consommables','Ravate Pro',7.5,'u'],
    ['Pinceau 50 mm','PIN-50','Consommables','Ravate Pro',5,'u'],
  ],
  menuis: [
    ['Porte intérieure 83 cm','PIN-P83','Portes','Ravate Pro',145,'u'],
    ['Bloc-porte isoplane','PIN-BP83','Portes','Ravate Pro',190,'u'],
    ['Tasseau 27×40','BOI-T2740','Bois','Négoce Bois',1.9,'m'],
    ['Contreplaqué 18 mm','BOI-CP18','Bois','Négoce Bois',28,'m²'],
    ['Lame de terrasse bois','BOI-LT21','Bois','Négoce Bois',42,'m²'],
    ['Lambourde bois classe 4','BOI-LAMB4','Bois','Négoce Bois',4.8,'m'],
    ['Fenêtre alu cyclonique 1 200 Pa','ALU-F1200','Menuiseries ext.','Ravate Pro',420,'u'],
    ['Paumelles (lot de 3)','QUI-PAUM','Quincaillerie','Ravate',6,'u'],
    ['Vis inox (boîte 200)','QUI-VIS','Quincaillerie','Ravate',14,'u'],
    ['Lasure 2,5 L','SIK-LAS25','Finition','Ravate Pro',32,'u'],
  ],
  carrel: [
    ['Grès cérame 60×60','CAR-GC60','Carreaux','Ravate Pro',24,'m²'],
    ['Faïence 20×40','CAR-FA2040','Carreaux','Ravate Pro',18,'m²'],
    ['Colle C2 25 kg','WEB-C225','Mortiers','Ravate',16,'sac'],
    ['Joint 5 kg','WEB-J5','Mortiers','Ravate',12,'u'],
    ['Croisillons 3 mm','ACC-CR3','Accessoires','Ravate',3,'u'],
    ['Primaire 5 L','WEB-PRIM5','Préparation','Ravate',22,'u'],
    ["Système d'étanchéité SPEC",'WEB-SPEC','Préparation','Ravate Pro',30,'u'],
    ["Bande d'angle SPEC",'WEB-BANDE','Préparation','Ravate Pro',14,'u'],
    ['Plinthe assortie','CAR-PL','Carreaux','Ravate Pro',4,'m'],
  ],
  couvr: [
    ['Tôle bac acier 0,75 mm S320GD','TOL-BAC','Couverture','Ravate Pro',18,'m²'],
    ['Faîtage','TOL-FAIT','Couverture','Ravate Pro',12,'m'],
    ['Gouttière alu','ZIN-GOU','Évacuation','Ravate',9,'m'],
    ['Descente EP Ø80','ZIN-DEP80','Évacuation','Ravate',7,'m'],
    ['Vis autoforeuses (100)','VIS-AF','Fixation','Ravate',15,'u'],
    ['Closoir mousse','TOL-CLOS','Couverture','Ravate',2.5,'u'],
    ['Membrane sous-toiture','MEM-ST','Couverture','Ravate Pro',3.5,'m²'],
    ['Crochet de sécurité','SEC-CRO','Fixation','Ravate Pro',1.2,'u'],
    ['Tôle aluminium bord de mer','TOL-ALU','Couverture','Ravate Pro',26,'m²'],
    ['Vis inox + rondelle EPDM (100)','VIS-INOX','Fixation','Ravate',32,'u'],
  ],
};

export const PROJETS = {
  filaos: { client: 'SCI Les Filaos', contact: 'M. Payet (gérant)', tel: '0692 45 12 78', addr: '18 rue du Four à Chaux, 97410 Saint-Pierre', type: 'Mise aux normes électrique · 6 logements', pct: 60, debut: '15/09/2026', fin: '10/10/2026', devis: ['DEV-2026-039'], facs: ['FAC-2026-028'], key: 'Filaos',
    etapes: [['Passage de gaines', true], ['Tableaux divisionnaires', true], ['Appareillage', false], ['Consuel et mise en service', false]], note: 'Accès par le portail côté parking. Clé chez le gardien.' },
  hoarau: { client: 'Mme Hoarau', contact: 'Mme Hoarau', tel: '0693 88 21 04', addr: '7 chemin Isautier, 97430 Le Tampon', type: 'Rénovation électrique cuisine', pct: 0, debut: '28/09/2026', fin: '29/09/2026', devis: ['DEV-2026-040'], facs: [], key: 'Hoarau',
    etapes: [['Dépose ancienne installation', false], ['Nouvelles prises et éclairage', false], ['Essais', false]], note: 'Prévoir la protection du plan de travail neuf.' },
  grondin: { client: 'M. Grondin', contact: 'M. Grondin', tel: '0692 30 67 15', addr: '22 rue Hubert Delisle, 97438 Sainte-Marie', type: 'Remplacement tableau', pct: 95, debut: '02/09/2026', fin: '05/10/2026', devis: ['DEV-2026-038'], facs: ['FAC-2026-027'], key: 'Grondin',
    etapes: [['Nouveau tableau posé', true], ['Raccordements', true], ['Réception client et PV', false]], note: 'Reste la signature du PV de réception.' },
};

export const DTU = {
  elec: [['NF C 15-100', 'Installations électriques basse tension (série 2024)']],
  plomb: [['NF DTU 60.1', 'Plomberie sanitaire'], ['NF DTU 60.11', 'Calcul des réseaux'], ['Arrêté 30/11/2005', 'Eau chaude à 50 °C max. aux points de toilette']],
  macon: [['NF DTU 20.1', 'Maçonnerie de petits éléments'], ['NF DTU 13.3', 'Dallages'], ['Eurocode 8', 'Sismicité : La Réunion en zone 2']],
  peintre: [['NF DTU 59.1', 'Revêtements de peinture en feuil mince']],
  menuis: [['NF DTU 36.5', 'Mise en œuvre des fenêtres et portes extérieures'], ['NF DTU 51.4', 'Platelages extérieurs en bois'], ['Guide CSTB Réunion', 'Menuiseries : 1 200 Pa minimum en zone cyclonique']],
  carrel: [['NF DTU 52.2', 'Carrelage collé'], ['SPEC', 'Protection à l\u2019eau sous carrelage en pièces humides']],
  couvr: [['NF DTU 40.35', 'Couverture en tôles d\u2019acier nervurées'], ['Fiche paracyclonique CSTB', 'Tôle ≥ 0,75 mm, acier S320GD minimum']],
  multi: [['Règles de l\u2019art', 'DTU du corps d\u2019état concerné']],
};

export const METIERS = [
  { key: 'elec', label: 'Électricien', short: 'électricité', taux: 48, ex: ['Rénovation tableau villa T4 à Saint-Paul', '4 prises + 2 points lumineux cuisine', "Brasseur d'air et prise clim chambre"] },
  { key: 'plomb', label: 'Plombier', short: 'plomberie', taux: 50, ex: ['Remplacement chauffe-eau 200 L', 'Salle de bain : WC suspendu + lavabo', 'Douche à l\u2019italienne 90×90 avec mitigeur', 'Réseau eau froide PER cuisine 8 m'] },
  { key: 'macon', label: 'Maçon', short: 'maçonnerie', taux: 42, ex: ['Mur de clôture parpaing 12 m²', 'Dalle béton 20 m² garage', 'Muret de soutènement 6 m', 'Étanchéité toiture-terrasse 25 m²'] },
  { key: 'peintre', label: 'Peintre', short: 'peinture', taux: 38, ex: ['Séjour 40 m² murs + plafond', 'Rebouchage et 2 couches chambre', 'Boiseries et portes en satin', 'Varangue 30 m² peinture façade'] },
  { key: 'menuis', label: 'Menuisier', short: 'menuiserie', taux: 45, ex: ['Pose de 3 portes intérieures', 'Terrasse bois 15 m²', 'Remplacement 2 fenêtres alu cycloniques', 'Placard sur mesure chambre'] },
  { key: 'carrel', label: 'Carreleur', short: 'carrelage', taux: 42, ex: ['Salle de bain 8 m² sol + faïence', 'Carrelage séjour grès cérame 35 m²', 'Douche à l\u2019italienne faïence 6 m²', 'Crédence cuisine 3 m²'] },
  { key: 'couvr', label: 'Couvreur', short: 'couverture', taux: 46, ex: ['Réfection toiture tôle 60 m²', 'Gouttières 24 m', 'Toiture bord de mer 40 m² à Saint-Leu', 'Remplacement faîtage et closoirs 12 m'] },
  { key: 'multi', label: 'Multi-services', short: 'multi-services', taux: 40, ex: ['Prise, mitigeur et retouche peinture', 'Remplacement lavabo et siphon', 'Rafraîchissement peinture studio 25 m²'] },
];

CAT_RAW.multi = [...CAT_RAW.elec.slice(16, 22), ...CAT_RAW.plomb.slice(3, 8), ...CAT_RAW.peintre.slice(0, 5)];
